[package]
name = "rust_programming"
version = "0.1.0"
authors = ["gaurava <gauc073@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
syn = "0.14.4"
quote = "0.6.3"
