[package]
name = "poa"
version = "0.1.0"
authors = ["gaurava <gauc073@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libp2p = "^0.13.1"
hex = "^0.4"